### PR TITLE
Added additional pages, assets, and custom colors. Lastly, refactored components

### PR DESCRIPTION
**Pull request by YouDontSayIt-dev**
List of things added:
Pages:
Queue Page
Settings Page

Assets
Queue Page Pictures

Custom Colors
Custom Text Colors
Custom Button Color

Screenshot of Pages
image
image

### CODE REVIEW

**Comment by Android-James** [comment]
omcimized.

try adding a bg-gradient in your main content div. exp w the colors. ur choice

**Comment by YouDontSayIt-dev** [comment]
Added a new component pala named topNavbar.js

**Review by Android-James — APPROVED** [review]

**Comment by YouDontSayIt-dev** [comment]
> 

will do

**Review by KirisakiXOnodera — APPROVED** [review]
omsim inom guys

**Pull request merged**
