### PR TITLE
Done refactoring responsiveness of playbar

### PR DESCRIPTION
**Pull request by YouDontSayIt-dev**

### CODE REVIEW

**Comment by Android-James** [comment]
please undo changes on search page first. naayos ko na conflict nyan

**Comment by Android-James** [comment]
pls also undo changes on footer and topnavbar.

**Comment by YouDontSayIt-dev** [comment]
image
image
image
image
image
image

**Review by yjhhjs — APPROVED** [review]

**Comment by YouDontSayIt-dev** [comment]
Pr closed

**Pull request closed without merging**
