### PR TITLE
Added header and footer to updated codebase, also used tailwind

### PR DESCRIPTION
**Pull request by YouDontSayIt-dev**
image
image

### CODE REVIEW

**Comment by YouDontSayIt-dev** [comment]
See image above, header and footer glitched with the sidebar

**Comment by Android-James** [comment]
Ako na dyan sa footer, then cocopy nalang ng iba after ko magawang component. prob sa div yung mali, yung height and yung padding left.

**Comment by Android-James** [comment]
https://www.youtube.com/watch?v=fYq5PXgSsbE&t=728s

**Comment by Android-James** [comment]
This is my div arrangement.

**Comment by YouDontSayIt-dev** [comment]
Noted, will apply changes to the branch

**Pull request closed without merging**
